modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Focamacho/VampiresNeedUmbrellas/issues"
license = "MIT-1.0"
[[mods]]
modId="vampiresneedumbrellas"
version="${file.jarVersion}"
displayName="Vampires Need Umbrellas"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas"
credits="Thanks to maxanier and Cheaterpaul, for making Vampirism"
authors="Focamacho"
description='''
Now vampires no longer need to fear the sun! This mod adds umbrellas that protect vampires from the sun.

There are 4 types of umbrellas: Iron, Gold, Diamond and Netherite. Each of them has a different durability that can be changed in the configuration file.

And each type of umbrella is available in 16 different colors.
'''
[[dependencies.vampiresneedumbrellas]]
    modId="vampirism"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vampiresneedumbrellas]]
    modId="curios"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"